{
 "title": "Task 2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free RAM (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes/1073741824",
     "legendFormat": "Free RAM (GB)"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "LA1" },
    { "expr": "node_load5", "legendFormat": "LA5" },
    { "expr": "node_load15", "legendFormat": "LA15" }
   ]
  },
  {
   "title": "Disk space (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{device=\"/dev/nvme0n1p6\",mountpoint=\"/\"}-node_filesystem_avail_bytes{device=\"/dev/nvme0n1p6\",mountpoint=\"/\"})/1073741824",
     "legendFormat": "{{mountpoint}} Used"
    },
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/nvme0n1p6\",mountpoint=\"/\"}/1073741824",
     "legendFormat": "{{mountpoint}} Size"
    }
   ]
  }
 ]
}